apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: post-install-app
  namespace: tap-install
spec:
  serviceAccountName: tap-install-sa
  fetch:
  - git:
      url: ssh://git@github.com/pakiheart/tap-gitops.git
      ref: origin/main
      secretRef: 
        name: sync-git-ssh
      subPath: clusters/cg-prod-run/cluster-config/post-install
  template:
  - ytt: {}
  deploy:
  - kapp:
      rawOptions:
      - --dangerous-override-ownership-of-existing-resources=true
      - --dangerous-allow-empty-list-of-resources=true
      - --diff-changes=true
