---
tap_install:
  values:
    profile: build
    ceip_policy_disclosed: true
    amr:
      observer:
        cloudevent_handler:
          endpoint: "https://amr-cloudevent-handler.view.tap.raltaf.io"
          liveness_period_seconds: 10
        ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIFHTCCBAWgAwIBAgISAyO9oplMG+c453kgSG6vyZIqMA0GCSqGSIb3DQEBCwUA
          MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
          EwJSMzAeFw0yMzExMDgxNjA3MTZaFw0yNDAyMDYxNjA3MTVaMDQxMjAwBgNVBAMT
          KWFtci1jbG91ZGV2ZW50LWhhbmRsZXIudmlldy50YXAucmFsdGFmLmlvMIIBIjAN
          BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArNPqSyBiWpVh0M/P7Yuxh/Jc3aNq
          UeiCkfdbTePUcygbGBzjKal3gEDZBqZwwyaUmAEk5Qjr5uGTf4fEjfhxDGEIkYlD
          H+o/c+8lzKCEhatu98Dk1SiyCMcTSBqdN4B5Rgbl7tp6mWbadE5lUjXlPRMUz8nc
          gCiSoeNnqEdNBYAdueoFYgCJ2H3B31Z+mOmCibdaiqxurBHvlBqXz99I5P9RRQ8f
          IH+TeNTSM4HRQyzggvee2HheIVjiY2h03q4DSv07LPovlAxLZvNbQf013QrGj6Zf
          GJYfSLM2VhsYCfwTJO0dU31apAMsYjJT4CDirwfXm4QCilxQ5x7aIE6DjwIDAQAB
          o4ICKTCCAiUwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
          BgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQfHaxuzYzNjDx/Y0vxivfZ
          l/N2VTAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDmH6+dixTCxjBVBggrBgEFBQcB
          AQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5vLmxlbmNyLm9yZzAiBggrBgEF
          BQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzA0BgNVHREELTArgilhbXItY2xv
          dWRldmVudC1oYW5kbGVyLnZpZXcudGFwLnJhbHRhZi5pbzATBgNVHSAEDDAKMAgG
          BmeBDAECATCCAQIGCisGAQQB1nkCBAIEgfMEgfAA7gB1AEiw42vapkc0D+VqAvqd
          MOscUgHLVt0sgdm7v6s52IRzAAABi6/nChgAAAQDAEYwRAIgWjQjSBFu2pOtk9/r
          v7gwTm/1usR3i5FRUifdZ9XH5N4CIAdnhOODlrUIGdBafun8HgJ1IEVf8iiq4SMj
          QcxERGEsAHUAO1N3dT4tuYBOizBbBv5AO2fYT8P0x70ADS1yb+H61BcAAAGLr+cK
          JQAABAMARjBEAiBWiinrOQ5mW2uCrUuttotN4w4XZ4DAguO987DHLQBm8wIgUoWg
          2B0E8L0HSOTUE9srFSLaxb6u7Vlaa0oneiae/78wDQYJKoZIhvcNAQELBQADggEB
          AFh8B+tJ3CjHerf5i8PpRCcErVP0M4Ymn33fU/GXwMUXGVFh/Y0pQEvwk4KiFyX5
          VZCkVJCa7VI/CPD0xzdjZ/BkdR1UmD6PllimQRwMfILEFeaC5GjveDuwJD6Tu0FZ
          ETb9sbMOkA8oEZT+fMQ8knK2GLzefgBi5ydQbRvQiFuuGe+twOCVCvbNMeQfztLw
          Ty4mI8gPvntA+3aSg9X2opwUc5g3xBhHgxIEoLJoTCpqXdQuf6Nz2sfrkSp5r83+
          ivMYai0Od9l17sxUpht2zYaDGMVJbHfoiMODHEJ0yiJECfk+c9YIHaJAwGO5npcg
          OVs4F0S0RY7rvk82mA9oo/U=
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
          WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
          RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
          AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
          R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
          sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
          NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
          Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
          /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
          AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
          Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
          FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
          AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
          Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
          gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
          PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
          ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
          CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
          lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
          avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
          yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
          yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
          hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
          HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
          MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
          nLRbwHOoq7hHwg==
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
          MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
          DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
          AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
          ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
          wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
          LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
          4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
          bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
          sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
          Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
          FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
          SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
          PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
          TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
          SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
          c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
          +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
          ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
          b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
          U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
          MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
          5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
          9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
          WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
          he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
          Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
          -----END CERTIFICATE-----
        auth:
          kubernetes_service_accounts:
            enable: true
            autoconfigure: true
            secret:
              ref: "amr-observer-editor-token"
    shared:
      ingress_domain: build.tap.raltaf.io
      image_registry:  
        project_path: "registry.harbor.learn.tapsme.org/tap-build"
    #supply_chain: basic
    supply_chain: testing_scanning
    #ootb_supply_chain_basic:
    ootb_supply_chain_testing_scanning:
      external_delivery: true
      gitops:
        deliverable_repository_owner: "pakiheart"
        deliverable_repository_name: "tap-gitops-deliverable"
        deliverable_branch: main
        deliverable_server_address: "ssh://git@github.com"
        #ssh_secret: ""
        ssh_secret: "git-auth"
        server_address: "ssh://git@github.com"
        repository_owner: "pakiheart"
        repository_name: "tap-gitops-config"
        branch: main
        # repository_prefix: git@github.com/tap-gitops/config-dir
      scanning:
        image:
          policy: scan-policy
        source:
          policy: scan-policy
  
    grype:
      namespace: dev
      targetImagePullSecret: "registries-credentials"
      metadataStore:
        url: "https://metadata-store.view.tap.raltaf.io"
        caSecret:
          name: store-ca-cert
          importFromNamespace: metadata-store-secrets
        authSecret:
          name: store-auth-token
          importFromNamespace: metadata-store-secrets

    namespace_provisioner:
      controller: false
      additional_sources:
      - git:
          url: ssh://git@github.com/pakiheart/tap-gitops
          ref: origin/main
          subPath: credentials
          secretRef:
            name: sync-git
            namespace: tanzu-sync
        path: _ytt_lib/workload-creds
      - git:
          url: ssh://git@github.com/pakiheart/tap-gitops
          ref: origin/main
          subPath: additional_resources
          secretRef:
            name: sync-git
            namespace: tanzu-sync
        path: _ytt_lib/workload-additional-resources
      gitops_install:
        url: ssh://git@github.com/pakiheart/tap-gitops
        ref: origin/main
        subPath: ns-provisioner
        secretRef:
          name: sync-git
          namespace: tanzu-sync
          create_export: true
      import_data_values_secrets:
      - name: tenant-secrets
        namespace: tap-install
        create_export: true
      overlay_secrets:
      - name: workload-git-ssh-overlay
        namespace: tap-install
        create_export: true
    package_overlays:
    - name: "ootb-supply-chain-testing-scanning"
      secrets: 
      - name: "ootb-supply-chain-overlay"
    - name: "ootb-templates"
      secrets: 
      - name: "ootb-template-overlay"
