#@ load("@ytt:data", "data")
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
  annotations:
    kapp.k14s.io/change-group: eso/secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: #@ data.values.tap_install.secrets.eso.aws.region
      auth:
        jwt:
          serviceAccountRef:
            name: tap-install-secrets
            namespace: tap-install