apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-e2e-testing-taskrun
  namespace: dev
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Security
    tekton.dev/tags: security
    tekton.dev/displayName: "e2e testing"
    tekton.dev/platforms: "linux/amd64"
spec:
  steps:
    - name: e2e-testing
      image:  registry.harbor.learn.tapsme.org/library/alpine-curl-jq@sha256:9d6c9b8d08e8cc17acf67b514706561265b26d0ced7a8d4f891f421d6ed476f7
      script: |
        #!/usr/bin/env bash
        sleep 30;
        result="$(curl -I -s https://tanzu-java-web-app-dev.run.tap.raltaf.io | head -n 1|cut -d$' ' -f2)"
        echo $result
        if [[ ${result} == "200" ]]; then
          echo "e2e-testing::PASSED"
        else
          echo "e2e-testing::FAILED"
          exit 1
        fi