---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: e2e-testing-cluster-template
spec:
  params:
    - name: serviceAccount
      default: default
  healthRule:
    singleConditionType: Ready
  lifecycle: tekton
  
  template:
    apiVersion: carto.run/v1alpha1
    kind: TaskRun
    metadata:
      name: -e2e-testing   
    spec:
   
      taskRef:
        name: tekton-e2e-testing-taskrun

      inputs:
        taskRef:
          kind: ClusterTask
          name: e2e-testing-clustertask
