#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: e2e-testing-cluster-template
spec:
  params:
    - name: serviceAccount
      default: default
  healthRule:
    singleConditionType: Ready
  lifecycle: tekton

  
  template:
    apiVersion: carto.run/v1alpha1
    kind: Task
    metadata:
      name: #@ data.values.workload.metadata.name + "-e2e-testing"
      labels: #@ merge_labels({ "app.kubernetes.io/component": "e2e-testing" })
    spec:
      #@ if/end hasattr(data.values.workload.spec, "serviceAccountName"):
      serviceAccountName: #@ data.values.workload.spec.serviceAccountName

      taskRef:
        name: tekton-e2e-testing-taskrun
      inputs:
        serviceAccount: #@ data.values.params.serviceAccount
        taskRef:
          kind: ClusterTask
          name: e2e-testing-clustertask
