apiVersion: v1
kind: Secret
metadata:
  name: ootb-cluster-delivery-overlay
  namespace: tap-install
type: Opaque
stringData:
  ootb-cluster-delivery-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:template", "template")
        
    #@ def replace_value_to_default(left, right):
    #@   if "default" in left:
    #@     return left
    #@   end
    #@   param = dict(left)
    #@   param.update({"default": param.pop("value")})
    #@   return param
    #@ end
    
    #@overlay/match by=overlay.subset({"apiVersion": "carto.run/v1alpha1", "kind": "ClusterDelivery","metadata":{"name":"delivery-basic"}}), expects="0+"
    ---
    spec:
      resources:
      #@overlay/match by="name", expects="0+"
      #@overlay/append
      - name: end-to-end-testing
        templateRef:
          kind: ClusterSourceTemplate
          name: delivery-source-template
        sources:
        - resource: deployer
          name: source