---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-tekton-clusterrolebinding
subjects:
- kind: ServiceAccount
  namespace: dev
  name: default
roleRef:
  kind: ClusterRole
  name: workload
  apiGroup: rbac.authorization.k8s.io