---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: sync-git
  namespace: tanzu-sync
spec:
  toNamespaces:
  - "*"

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: sync-git
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: se/sync-git
    kapp.k14s.io/change-rule.0: "upsert after upserting tanzu-sync-secrets"    
spec:
  fromNamespace: tanzu-sync
