---
secrets:
  eso:
    aws:
      region: us-west-2
      tanzu_sync_secrets:
        role_arn: arn:aws:iam::017529031426:role/ra-tap-build--tanzu-sync-secrets
    remote_refs:
      sync_git:
        ssh:
          private_key:
            key: dev/ra-tap-build/tanzu-sync/sync-git-ssh
            property: ssh-privatekey
          known_hosts:
            key: dev/ra-tap-build/tanzu-sync/sync-git-ssh
            property: ssh-knownhosts
      install_registry_dockerconfig:
        dockerconfigjson:
          key: dev/ra-tap-build/tanzu-sync/install-registry-dockerconfig
