---
tap_install:
  values:
    profile: run
    ceip_policy_disclosed: true
    amr:
      observer:
        cloudevent_handler:
          endpoint: "https://amr-cloudevent-handler.view.tap.raltaf.io"
          liveness_period_seconds: 10
        auth:
          kubernetes_service_accounts:
            enable: true
            autoconfigure: true
            secret:
              ref: "amr-observer-editor-token"     
    shared:
      ingress_domain: run.tap.raltaf.io
      ingress_issuer: letsencrypt-production
    supply_chain: basic
    contour:
      envoy:
        service:
          type: LoadBalancer
    appliveview_connector:
      backend:
        ingressEnabled: true
        host: appliveview.view.tap.raltaf.io
    cnrs:
      domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
    namespace_provisioner:
      controller: false
      gitops_install:
        url: ssh://git@github.com/pakiheart/tap-gitops
        ref: origin/main
        subPath: ns-provisioner
        secretRef:
          name: sync-git
          namespace: tanzu-sync
          create_export: true
      additional_sources:
      - git:
          url: ssh://git@github.com/pakiheart/tap-gitops
          ref: origin/main
          subPath: credentials
          secretRef:
            name: sync-git
            namespace: tanzu-sync
        path: _ytt_lib/workload-creds
      import_data_values_secrets:
      - name: tenant-secrets
        namespace: tap-install
        create_export: true
    api_auto_registration:
      tap_gui_url: "https://tap-gui.view.tap.raltaf.io"
      cluster_name: run
    # package_overlays:
    # - name: "ootb-delivery-basic"
    #   secrets: 
    #   - name: "ootb-cluster-delivery-overlay"
 
