#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: tekton
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgr"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgr"
spec:
  serviceAccountName: tap-installer-sa
  packageRef:
    refName: tekton.tanzu.vmware.com
    versionSelection:
      constraints: ">=0.50.1+tanzu.3"