#@ load("@ytt:data", "data")

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: sync-git
  annotations:
  tekton.dev/git-0: github.com
spec:
  fromNamespace: tanzu-sync
