apiVersion: carto.run/v1alpha1
kind: ClusterRunTemplate
metadata:
  name: tekton-e2e-testing-run-template
spec:
  template:
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: e2e-testing-$(runnable.metadata.name)$-
      labels: $(runnable.metadata.labels)$
    spec:
      serviceAccountName: $(runnable.spec.inputs.serviceAccount)$
      taskRef:
        name: tekton-e2e-testing-taskrun
